/*
 * This Java source file was generated by the Gradle 'init' task.
 */



package edu.isu.cs.cs2263;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Insets;
import javafx.geometry.Orientation;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    /**
     * The main entry point for all JavaFX applications.
     * The start method is called after the init method has returned,
     * and after the system is ready for the application to begin running.
     *
     * <p>
     * NOTE: This method is called on the JavaFX Application Thread.
     * </p>
     *
     * @param primaryStage the primary stage for this application, onto which
     *                     the application scene can be set.
     *                     Applications may create other stages, if needed, but they will not be
     *                     primary stages.
     * @throws Exception if something goes wrong
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Course View");
        HBox hbox1 = new HBox();

        Button loadButton = new Button("Load Data");
        hbox1.getChildren().add(loadButton);
        hbox1.setAlignment(Pos.CENTER_RIGHT);

        Label label = new Label("Is taking");

        ObservableList<String> studentList = FXCollections.<String>observableArrayList("John Oliver", "Jay Gatsby");
        ObservableList<String> courseList = FXCollections.<String>observableArrayList("ENGL 1101", "MATH 1175", "CS 1181");

        //Create student listview
        ListView<String> students = new ListView<>(studentList);
        students.setOrientation(Orientation.VERTICAL);
        students.setPrefSize(120, 100 );

        // Create the Student VBox
        VBox studentSelection = new VBox();
        // Set Spacing to 10 pixels
        studentSelection.setSpacing(10);
        // Add the Label and the List to the VBox
        studentSelection.getChildren().addAll(students);


        ListView<String> courses = new ListView<>(courseList);
        courses.setOrientation(Orientation.VERTICAL);
        courses.setPrefSize(120, 100 );

        // Create the Course VBox
        VBox courseSelection = new VBox();
        // Set Spacing to 10 pixels
        courseSelection.setSpacing(10);
        // Add the Label and the List to the VBox
        courseSelection.getChildren().addAll(courses);


        //root (main pane)
        GridPane root = new GridPane();
        root.setMinSize(400, 200);
        root.setPadding(new Insets(20)); // space between elements and window border
        root.setVgap(5);
        root.setHgap(10);
        root.add(hbox1, 0,2);
        root.add(studentSelection, 0,1);
        root.add(label, 1,1);
        root.add(courseSelection, 2,1);
        Scene scene = new Scene(root, 400, 200);

        primaryStage.setScene(scene);

        primaryStage.show();
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}